# Generated by Django 3.1.2 on 2020-10-24 07:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201024_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
