# Generated by Django 3.1.2 on 2020-10-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='shortdescription',
            field=models.CharField(default='This is a shor description of my Article', max_length=100),
        ),
    ]
