# Generated by Django 3.1.2 on 2020-10-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact_shortdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(default='img/slider2.jpg', upload_to='article_cover/'),
        ),
    ]
