# Generated by Django 3.1.2 on 2020-10-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contact_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Post',
        ),
    ]
