# Generated by Django 3.1.2 on 2020-10-26 15:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='striped_desc',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
