# Generated by Django 3.1.2 on 2020-10-26 15:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_post_striped_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='striped_desc',
            field=ckeditor.fields.RichTextField(default='', editable=False),
        ),
    ]
